name: CI

on:
  push:
    branches:
      - main
      - text-draw
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Test `cargo clippy/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal --target wasm32-unknown-unknown
      - uses: extractions/setup-just@v1
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy --all

      # Setup everything for release builds
      - run: |
          mkdir ./bin
          wget https://github.com/WebAssembly/binaryen/releases/download/version_114/binaryen-version_114-x86_64-linux.tar.gz
          wget https://github.com/WebAssembly/wabt/releases/download/1.0.33/wabt-1.0.33-ubuntu.tar.gz
          tar -xf binaryen-version_114-x86_64-linux.tar.gz-x86_64-linux.tar.gz
          tar -xf wabt-1.0.33-ubuntu.tar.gz
          mv binaryen-version_114/bin/* ./bin
          mv wabt-1.0.33/bin/* ./bin

      - run: |
          PATH="$(pwd)/bin:$PATH" just export-release-web
          mkdir exports && mv ./export-release.html exports/index.html
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: exports
